# Generated by Django 5.2.2 on 2025-06-17 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_message', models.CharField(default='Idle', max_length=255)),
                ('command', models.CharField(default='NONE', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='botactivitylog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botactivitylog',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
