# Generated by Django 5.2.2 on 2025-06-20 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_monitor', '0003_botactivitylog_bot_id_botstatus_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botstatus',
            name='bot_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='botstatus',
            name='jobs_scraped_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botstatus',
            name='proposals_sent_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='botstatus',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
