# Generated by Django 5.2.2 on 2025-06-12 21:47

# In the generated migration file (e.g., main_site/migrations/xxxx_create_initial_superuser.py)
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    # IMPORTANT: Change username, email, and password
    # Do NOT commit a real password to your repository.
    # Consider setting a known temporary password and changing it immediately after first login.
    # Or, for better security, load these from environment variables just for this migration.
    username = os.environ.get('INITIAL_SUPERUSER_NAME', 'admin_temp')
    email = os.environ.get('INITIAL_SUPERUSER_EMAIL', 'admin_temp@example.com')
    password = os.environ.get('INITIAL_SUPERUSER_PASSWORD', 'TemporaryPassword123!') # NOT SECURE FOR LONG TERM

    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            email=email,
            password=make_password(password), # Hashes the password
            is_superuser=True,
            is_staff=True
        )
        print(f"Superuser {username} created by migration.")
    else:
        print(f"Superuser {username} already exists or placeholder not unique.")

class Migration(migrations.Migration):
    dependencies = [
        # Add dependency on the previous auth migration or your last user-related migration
        ('auth', '0012_alter_user_first_name_max_length'), # Example, check your latest auth migration
    ]
    operations = [
        migrations.RunPython(create_superuser),
    ]
