# Generated by Django 5.2.2 on 2026-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='answered_modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='module_results',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
