# Generated by Django 5.2.2 on 2026-06-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_usercourseprogress_answered_modules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpromocode',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedpromocode',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='printful_sync_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='product_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='required_dev_tier',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='merchitem',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=8),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='base_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
