# Generated by Django 5.2.2 on 2026-06-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_generatedpromocode_redeemed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchitem',
            name='required_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
