# Generated by Django 5.2.2 on 2026-07-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_merchitem_required_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('printful_order_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='processed', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
