# Generated by Django 5.2.2 on 2026-07-15 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_fulfilledorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfilledorder',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fulfilledorder',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fulfilledorder',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fulfilledorder',
            name='pf_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fulfilledorder',
            name='recipient',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fulfilledorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StoreCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='available', max_length=20)),
                ('payment_intent', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='academy.fulfilledorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
